// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// clang-format off
#include <Jolt/Jolt.h>
// clang-format on
#include <Jolt/Math/Float3.h>
#include <Jolt/Math/Float4.h>
#include <Zahlen/Common.h>
#include <Zahlen/Entity.hpp>
#include <Zahlen/Error.hpp>
#include <cstdint>
#include <expected>
#include <string>
#include <vector>

// ============================================================================
// Scenes as data.
//
// The structs below ARE the scene format. There is no schema file, no parser
// table and no registry of field names: they are plain reflected structs, so
// any reflection-driven serialiser can walk them, and adding a field to a
// struct here adds it to the document format in the same edit. A field's
// default in the declaration is its default in a document, which is what lets
// a scene file say only what differs from the defaults.
//
// This header is deliberately format-free. Reading and writing a scene as TOML
// lives in extras/toml/SceneTOML.hpp, which binds these structs to the
// reflection-driven parser in extras/toml/ and provides
// Scene::InstantiateFromTOML(). Core never reaches for it: the engine's own
// fallback preset (DefaultPreset) builds one of these structs in C++ and calls
// Instantiate() directly, so a scene description is usable with no document
// layer compiled in at all.
//
// Instantiating is a pure function of the description plus the engine it is
// given -- no ambient engine, no process-global scene state. Two engines can
// hold the same Scene at once, and re-instantiating the same description
// produces the same scene, which is the property the render tests need.
//
// Vectors are Jolt's plain storage types (JPH::Float3, JPH::Float4) rather
// than std::array, so a field goes straight into the engine --
// JPH::Vec3(t.position) -- with no unpacking helper in between. They still read
// as `[x, y, z]` in a document; see the TOMLVector specialisations in
// extras/toml/SceneTOML.hpp.
// Positions are Float3 and not Double3 on purpose: RVec3 is only DVec3 in a
// JPH_DOUBLE_PRECISION build, so a Double3 field would stop converting in the
// default one, and no hand-authored scene needs 15 significant digits.
//
// Colours are linear RGBA in [0,1] unless a field says otherwise; angles are
// degrees, because that is what the people writing these files think in.
// ============================================================================

namespace ZHLN {

class Engine;

namespace Scene {

/// Local transform. Euler degrees, in the engine's XYZ order.
struct Transform {
    JPH::Float3 position = {0.0f, 0.0f, 0.0f};
    JPH::Float3 rotation = {0.0f, 0.0f, 0.0f};
    JPH::Float3 scale    = {1.0f, 1.0f, 1.0f};
};

/// What geometry an entity is. `Prefab` reads the `source` glTF/GLB path;
/// every other shape is generated by CreativeWorksFactory.
enum class ShapeKind : uint8_t { Box, Plane, Prefab };

/// The rigid body an entity gets, if any. Static bodies never move and carry
/// no interpolation state; Dynamic ones fall.
enum class BodyKind : uint8_t { None, Static, Dynamic };

/// Surface appearance. Emission is a shading term plus a glow contribution --
/// it is not a light source, which is both the glTF meaning and Babylon's.
///
/// `emissive` is in engine HDR units, not glTF's [0,1]: blit.slang tonemaps
/// with `hdrColor *= 0.015`, so 1.0 renders at roughly 10/255 and 100 is about
/// the tonemapper's white point. A scene that wants neon should say ~80, which
/// is what the importer produces for a glTF emissiveFactor of 0.8 (see
/// kGLTFEmissiveDisplayScale in Zahlen/ModelPrefab.hpp).
struct SceneMaterial {
    JPH::Float4 baseColor = {0.8f, 0.4f, 0.2f, 1.0f};
    float       roughness = 0.5f;
    float       metallic  = 0.0f;
    JPH::Float3 emissive  = {0.0f, 0.0f, 0.0f};

    /// Spawns a cheap point light per emissive part. Off by default and
    /// approximate -- see SpawnParams::emissiveVirtualLights.
    bool emissiveVirtualLights = false;
};

struct SceneEntity {
    std::string name;
    ShapeKind   shape = ShapeKind::Box;

    /// Box half extents. Ignored by the other shapes.
    JPH::Float3 halfExtents = {0.5f, 0.5f, 0.5f};
    /// Plane half size. Ignored by the other shapes.
    float extent = 10.0f;
    /// Asset path for ShapeKind::Prefab.
    std::string source;

    Transform     transform;
    BodyKind      body = BodyKind::None;
    SceneMaterial material;
};

struct SceneLight {
    std::string name;
    /// One of the LightType enumerators: Directional, Point, Spot, Area, Sun.
    std::string type     = "Point";
    JPH::Float3 position = {0.0f, 3.0f, 0.0f};
    /// Euler degrees, like Transform::rotation. It matters for the oriented
    /// types: LightingSystem packs a Directional/Spot/Sun direction from the
    /// world matrix, not from `direction` below, which the sun's cascade path
    /// reads instead.
    JPH::Float3 rotation = {0.0f, 0.0f, 0.0f};
    /// Normalized on instantiation, so a document can write [0.4, 1.0, 0.3]
    /// and mean the direction rather than the length.
    JPH::Float3 direction   = {0.0f, -1.0f, 0.0f};
    JPH::Float3 color       = {1.0f, 1.0f, 1.0f};
    float       intensity   = 100.0f;
    float       radius      = 0.5f;
    float       range       = 20.0f;
    int32_t     shadowLayer = -1;
};

struct SceneCamera {
    JPH::Float3 position = {0.0f, 2.0f, 8.0f};
    float       yaw      = -90.0f;
    float       pitch    = 0.0f;
    float       fov      = 60.0f;
};

/// The knobs a scene is allowed to set on the global settings entity. Kept
/// deliberately small: this is the part of the renderer a scene author owns,
/// not a mirror of PostProcessSettingsComponent.
///
/// Every default here is PostProcessSettingsComponent's default. That is a
/// requirement, not a coincidence: Instantiate writes all of these
/// unconditionally, so a field whose default disagreed with the engine's would
/// silently restyle any scene that left the key out -- the opposite of "a
/// document says what differs".
struct SceneEnvironment {
    float       ambientExposure = 25.0f;
    float       giIntensity     = 1.2f;
    JPH::Float3 skyZenith       = {0.003f, 0.008f, 0.020f};
    JPH::Float3 skyHorizon      = {0.015f, 0.035f, 0.080f};
    JPH::Float3 skyGround       = {0.001f, 0.001f, 0.003f};

    /// Screen-space and ray-traced reflections. Scene-owned because whether a
    /// scene is worth tracing reflections for is a property of the scene.
    bool enableSSR = true;
    bool enableRTR = false;
};

/// A whole scene. This is the root table of the document.
struct Scene {
    std::string              name = "untitled";
    SceneCamera              camera;
    SceneEnvironment         environment;
    std::vector<SceneEntity> entities;
    std::vector<SceneLight>  lights;
};

/// What Instantiate created, in declaration order, so a caller can address the
/// entities it just asked for without searching the registry by name.
struct Instance {
    std::vector<Entity> entities;
    std::vector<Entity> lights;
};

enum class SceneError : uint8_t {
    MaterialCreationFailed = 1,
    PrefabNotFound,
    UnknownLightType,
};

/// Builds `description` into `engine`. Additive: it does not clear what is
/// already there, so a caller that wants a clean slate resets the engine
/// first.
///
/// The textual counterpart, Scene::InstantiateFromTOML(), is declared in
/// extras/toml/SceneTOML.hpp.
[[nodiscard]] auto Instantiate(Engine& engine, const Scene& description) -> std::expected<Instance, Error>;

} // namespace Scene
} // namespace ZHLN
