// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

// clang-format off
#include <Jolt/Jolt.h>
// clang-format on
#include <Jolt/Math/Float3.h>
#include <Jolt/Math/Float4.h>
#include <Zahlen/Common.h>
#include <Zahlen/Entity.hpp>
#include <Zahlen/Error.hpp>
#include <Zahlen/Core/AssetID.hpp>
#include <Zahlen/Render/Types.hpp>
#include <cstdint>
#include <expected>
#include <optional>
#include <string>
#include <vector>

// Scenes as data: the structs below ARE the scene format. There is no schema file,
// parser table or field-name registry -- they are plain reflected structs, so adding
// a field here adds it to the document format in the same edit, and a field's
// declared default is its document default (a scene file says only what differs).
//
//   * Format-free on purpose: document I/O is the reflection-driven layer in
//     extras/toml/TOML.hpp plus the Jolt vector bindings in SceneTOML.hpp, meeting
//     this header at Scene::Instantiate() and Scene::Extract(). Core never reaches
//     for it -- DefaultPreset builds these structs in C++ and calls Instantiate().
//   * Instantiating is a pure function of the description and the engine: no global
//     scene state, and re-instantiating reproduces the same scene.
//   * Vectors are Jolt's storage types (Float3/Float4) so a field goes straight into
//     the engine, yet still read as `[x, y, z]` in a document. Float3, not Double3:
//     RVec3 is only DVec3 in a JPH_DOUBLE_PRECISION build.
//   * Colours are linear RGBA in [0,1] unless stated; angles are degrees.

namespace ZHLN {

class Engine;
struct Camera;

namespace ECS {
class Registry;
}

namespace Scene {

// Local transform. Euler degrees, in the engine's XYZ order.
struct Transform {
    JPH::Float3 position = {0.0f, 0.0f, 0.0f};
    JPH::Float3 rotation = {0.0f, 0.0f, 0.0f};
    JPH::Float3 scale    = {1.0f, 1.0f, 1.0f};
};

// What geometry an entity is. `Prefab` reads the `source` glTF/GLB path;
// every other shape is generated by CreativeWorksFactory.
enum class ShapeKind : uint8_t { Box, Plane, Prefab };

// The rigid body an entity gets, if any. Static bodies never move and carry
// no interpolation state; Dynamic ones fall.
enum class BodyKind : uint8_t { None, Static, Dynamic };

// Surface appearance. Emission is a shading term plus a glow contribution, not a
// light source (the glTF and Babylon meaning).
//
// `emissive` is in engine HDR units, not glTF's [0,1]: blit.slang tonemaps with
// `hdrColor *= 0.015`, so neon is ~80 -- what the importer produces for a glTF
// emissiveFactor of 0.8 (kGLTFEmissiveDisplayScale in ModelPrefab.hpp).
struct SceneMaterial {
    JPH::Float4 baseColor = {0.8f, 0.4f, 0.2f, 1.0f};
    float       roughness = 0.5f;
    float       metallic  = 0.0f;
    JPH::Float3 emissive  = {0.0f, 0.0f, 0.0f};

    // Spawns a cheap point light per emissive part. Off by default and
    // approximate -- see SpawnParams::emissiveVirtualLights.
    bool emissiveVirtualLights = false;
};

struct SceneEntity {
    std::string name;
    ShapeKind   shape = ShapeKind::Box;

    // Box half extents. Ignored by the other shapes.
    JPH::Float3 halfExtents = {0.5f, 0.5f, 0.5f};
    // Plane half size. Ignored by the other shapes.
    float extent = 10.0f;
    // Asset path for ShapeKind::Prefab.
    std::string source;

    Transform     transform;
    BodyKind      body = BodyKind::None;
    SceneMaterial material;
};

struct SceneLight {
    std::string name;
    // One of the LightType enumerators: Directional, Point, Spot, Area, Sun.
    std::string type     = "Point";
    JPH::Float3 position = {0.0f, 3.0f, 0.0f};
    // Euler degrees, like Transform::rotation, and what matters for the oriented
    // types: LightingSystem packs a Directional/Spot/Sun direction from the world
    // matrix, not from `direction` below (which the sun's cascade path reads).
    JPH::Float3 rotation = {0.0f, 0.0f, 0.0f};
    // Normalized on instantiation, so a document can write [0.4, 1.0, 0.3] and mean
    // the direction, not the length.
    JPH::Float3 direction   = {0.0f, -1.0f, 0.0f};
    JPH::Float3 color       = {1.0f, 1.0f, 1.0f};
    float       intensity   = 100.0f;
    float       radius      = 0.5f;
    float       range       = 20.0f;
    int32_t     shadowLayer = -1;
};

struct SceneCamera {
    JPH::Float3 position = {0.0f, 2.0f, 8.0f};
    float       yaw      = -90.0f;
    float       pitch    = 0.0f;
    float       fov      = 60.0f;
};

// The knobs a scene may set on the global settings entity: the part of the
// renderer a scene author owns, deliberately not a mirror of
// PostProcessSettingsComponent.
//
// Every default here must equal PostProcessSettingsComponent's: Instantiate writes
// all of these unconditionally, so a disagreeing default would silently restyle any
// scene that left the key out.
struct SceneEnvironment {
    float       ambientExposure = 25.0f;
    float       giIntensity     = 1.2f;
    JPH::Float3 skyZenith       = {0.003f, 0.008f, 0.020f};
    JPH::Float3 skyHorizon      = {0.015f, 0.035f, 0.080f};
    JPH::Float3 skyGround       = {0.001f, 0.001f, 0.003f};

    // Scene-owned because whether a scene is worth tracing reflections for is a
    // property of the scene.
    bool enableSSR = true;
    bool enableRTR = false;

    // Final Blit colour style. Tonemapper values mirror blit.slang:
    // 0 = Linear, 1 = ACES, 2 = Reinhard, 3 = Neutral.
    float       exposure      = 0.015f;
    float       bloomStrength = 0.5f;
    float       contrast      = 1.0f;
    float       saturation    = 1.0f;
    int32_t     tonemapper    = 1;
    JPH::Float3 colorFilter   = {1.0f, 1.0f, 1.0f};
};

// A whole scene. This is the root table of the document.
struct Scene {
    std::string              name = "untitled";
    SceneCamera              camera;
    SceneEnvironment         environment;
    std::vector<SceneEntity> entities;
    std::vector<SceneLight>  lights;
};

// What Instantiate created, in declaration order, so a caller can address the
// entities it just asked for without searching the registry by name.
struct Instance {
    std::vector<Entity> entities;
    std::vector<Entity> lights;
};

enum class SceneError : uint8_t {
    MaterialCreationFailed = 1,
    PrefabNotFound,
    UnknownLightType,
};

// Builds `description` into `engine`. Additive: it does not clear what is already
// there. The textual half -- reading a document -- is ReflectTOML::TryParse.
[[nodiscard]] auto Instantiate(Engine& engine, const Scene& description) -> std::expected<Instance, ErrorCode>;

// Rebuilds the description that would reproduce the world @p engine holds: the
// mirror image of Instantiate(), kept in step by the reflective copy in Scene.cpp
// rather than by two hand-written field lists.
//
// Scene content is what Instantiate put there -- an entity carrying
// SceneSourceComponent (geometry) or SceneLightTagComponent (lights). Runtime-spawned
// geometry and terrain are not expressible in the schema, and an emissive prefab's
// virtual lights would be duplicated on reload, so none of them are extracted;
// skipped entities are counted and logged once, never dropped silently.
//
// `Scene::name` keeps its default: a running world carries no scene name, so a caller
// saving to a file sets it from the path.
[[nodiscard]] auto Extract(Engine& engine) -> Scene;

// How Extract() reads a material's CPU-side factors: base colour and emissive live
// in the material table the render context owns, not on the entity. Taking the whole
// RenderContext would make this overload uncallable without a device, so it asks for
// the one operation it needs -- a function pointer plus userdata, the shape of
// GUI::TextEdit::ClipboardSink.
//
// A default-constructed lookup (`find == nullptr`) is the device-free case: those two
// fields keep their struct defaults, so a scene can be round-tripped with no GPU.
struct MaterialLookup {
    const void*             userdata = nullptr;
    std::optional<Material> (*find)(const void* userdata, MaterialID id) = nullptr;
};

// Extract() without the engine: the same walk over a camera and a registry. Every
// field comes out of the registry except base colour and emissive, which @p materials
// resolves; omit it and those two stay at their defaults.
[[nodiscard]] auto Extract(const Camera& camera, const ECS::Registry& registry, MaterialLookup materials = {}) -> Scene;

} // namespace Scene
} // namespace ZHLN
