// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <Zahlen/Common.h>
#include <Zahlen/Entity.hpp>
#include <Zahlen/Error.hpp>
#include <array>
#include <cstdint>
#include <expected>
#include <string>
#include <string_view>
#include <vector>

// ============================================================================
// Scenes as data.
//
// The structs below ARE the scene format. There is no schema file, no parser
// table and no registry of field names: Zahlen/TOML.hpp walks these
// declarations with static reflection, so
//
//     ZHLN::Reflect::SerializeTOML(scene)          // scene -> text
//     ZHLN::ReflectTOML::TryParse<Scene>(text)     // text  -> scene
//
// are both derived from the type, and adding a field to a struct here adds it
// to the file format in the same edit. A field's default in the declaration is
// its default in the document, because a missing key leaves the field alone --
// so a scene file says what differs from the defaults and nothing else.
//
// TOML rather than JSON because these are hand-edited and reviewed: comments
// survive, [[entities]] reads as a list of things rather than a bracket forest,
// and `position = [0.0, 8.0, 0.0]` diffs one line at a time.
//
// Instantiating is a pure function of the description plus the engine it is
// given -- no ambient engine, no process-global scene state. Two engines can
// hold the same Scene at once, and re-instantiating the same description
// produces the same scene, which is the property the render tests need.
//
//     const auto scene = ZHLN::ReflectTOML::TryParse<ZHLN::Scene::Scene>(text);
//     const auto built = ZHLN::Scene::Instantiate(engine, *scene);
//
// Colours are linear RGBA in [0,1] unless a field says otherwise; angles are
// degrees, because that is what the people writing these files think in.
// ============================================================================

namespace ZHLN {

class Engine;

namespace Scene {

/// Local transform. Euler degrees, in the engine's XYZ order.
struct Transform {
    std::array<float, 3> position = {0.0f, 0.0f, 0.0f};
    std::array<float, 3> rotation = {0.0f, 0.0f, 0.0f};
    std::array<float, 3> scale    = {1.0f, 1.0f, 1.0f};
};

/// What geometry an entity is. `Prefab` reads the `source` glTF/GLB path;
/// every other shape is generated by CreativeWorksFactory.
enum class ShapeKind : uint8_t { Box, Plane, Prefab };

/// The rigid body an entity gets, if any. Static bodies never move and carry
/// no interpolation state; Dynamic ones fall.
enum class BodyKind : uint8_t { None, Static, Dynamic };

/// Surface appearance. Emission is a shading term plus a glow contribution --
/// it is not a light source, which is both the glTF meaning and Babylon's.
/// Values above 1.0 are the KHR_materials_emissive_strength case and are
/// allowed here for the same reason.
struct SceneMaterial {
    std::array<float, 4> baseColor = {0.8f, 0.4f, 0.2f, 1.0f};
    float                roughness = 0.5f;
    float                metallic  = 0.0f;
    std::array<float, 3> emissive  = {0.0f, 0.0f, 0.0f};

    /// Spawns a cheap point light per emissive part. Off by default and
    /// approximate -- see SpawnParams::emissiveVirtualLights.
    bool emissiveVirtualLights = false;
};

struct SceneEntity {
    std::string name;
    ShapeKind   shape = ShapeKind::Box;

    /// Box half extents. Ignored by the other shapes.
    std::array<float, 3> halfExtents = {0.5f, 0.5f, 0.5f};
    /// Plane half size. Ignored by the other shapes.
    float extent = 10.0f;
    /// Asset path for ShapeKind::Prefab.
    std::string source;

    Transform     transform;
    BodyKind      body = BodyKind::None;
    SceneMaterial material;
};

struct SceneLight {
    std::string name;
    /// One of the LightType enumerators: Directional, Point, Spot, Area, Sun.
    std::string          type        = "Point";
    std::array<float, 3> position    = {0.0f, 3.0f, 0.0f};
    std::array<float, 3> direction   = {0.0f, -1.0f, 0.0f};
    std::array<float, 3> color       = {1.0f, 1.0f, 1.0f};
    float                intensity   = 100.0f;
    float                radius      = 0.5f;
    float                range       = 20.0f;
    int32_t              shadowLayer = -1;
};

struct SceneCamera {
    std::array<float, 3> position = {0.0f, 2.0f, 8.0f};
    float                yaw      = -90.0f;
    float                pitch    = 0.0f;
    float                fov      = 60.0f;
};

/// The knobs a scene is allowed to set on the global settings entity. Kept
/// deliberately small: this is the part of the renderer a scene author owns,
/// not a mirror of PostProcessSettingsComponent.
struct SceneEnvironment {
    float                ambientExposure = 1.0f;
    float                giIntensity     = 1.0f;
    std::array<float, 3> skyZenith       = {0.05f, 0.10f, 0.20f};
    std::array<float, 3> skyHorizon      = {0.35f, 0.45f, 0.60f};
    std::array<float, 3> skyGround       = {0.10f, 0.10f, 0.10f};
};

/// A whole scene. This is the root table of the document.
struct Scene {
    std::string              name = "untitled";
    SceneCamera              camera;
    SceneEnvironment         environment;
    std::vector<SceneEntity> entities;
    std::vector<SceneLight>  lights;
};

/// What Instantiate created, in declaration order, so a caller can address the
/// entities it just asked for without searching the registry by name.
struct Instance {
    std::vector<Entity> entities;
    std::vector<Entity> lights;
};

enum class SceneError : uint8_t {
    MaterialCreationFailed = 1,
    PrefabNotFound,
    UnknownLightType,
};

/// Builds `description` into `engine`. Additive: it does not clear what is
/// already there, so a caller that wants a clean slate resets the engine
/// first.
[[nodiscard]] auto Instantiate(Engine& engine, const Scene& description) -> std::expected<Instance, Error>;

/// Reads a scene document and instantiates it in one step.
[[nodiscard]] auto InstantiateFromTOML(Engine& engine, std::string_view tomlText) -> std::expected<Instance, Error>;

} // namespace Scene
} // namespace ZHLN
