#!/usr/bin/env python3
# configure_assets.py
import os
import sys
import json


def escape_ninja(path):
    # Ninja uses '$ ' to escape spaces in target and dependency paths
    return path.replace(" ", "$ ")


def discover_blend_files(search_path):
    """Recursively scans directories to discover valid Blend files."""
    blend_files = []
    for root, _, files in os.walk(search_path):
        norm_root = root.replace("\\", "/").lower()
        if any(
            p in norm_root
            for p in [
                "resources/intermediate",
                "exported_assets",
            ]
        ):
            continue
        for file in files:
            if file.endswith(".blend") and not file.startswith("."):
                if "void" in file.lower():
                    continue
                blend_files.append(os.path.join(root, file).replace("\\", "/"))
    return blend_files


def generate_ninja(output_file, zcook_executable, source_dir):
    escaped_zcook = escape_ninja(zcook_executable)
    escaped_script = escape_ninja(
        os.path.join(source_dir, "tools", "export_metadata.py").replace("\\", "/")
    )
    intermediate_root = os.path.join(source_dir, "resources", "intermediate").replace(
        "\\", "/"
    )

    ninja_content = f"""# Automatically generated by configure_assets.py
ninja_required_version = 1.3
builddir = build_assets

rule blender_extract
  command = blender -b $in -P "{escaped_script}" -- $in "{intermediate_root}"
  description = BLENDER $in

rule zmesh
  command = "{escaped_zcook}" mesh --meta "$meta" --id "$id" -i $in -o $out
  description = ZMESH $id

rule ztex
  command = "{escaped_zcook}" tex -i $in -o $out
  description = ZTEX $in

rule zglb
  command = "{escaped_zcook}" glb --meta $in -o $out
  description = ZGLB $in

rule zpak
  command = "{escaped_zcook}" pak -o $out -i $in
  description = ZPAK $out
  pool = console
"""

    compiled_targets = []
    glb_targets = []
    manifest_entries = []

    # Find master level blend sources
    blend_files = discover_blend_files(source_dir)

    # Pre-calculate namespaced metadata dependencies using absolute paths
    # This ensures both the build graph and generator rules share identical namespaced targets
    meta_deps_list = []
    for b in blend_files:
        abs_blend = os.path.abspath(b)
        abs_source = os.path.abspath(source_dir)
        rel_path = os.path.relpath(abs_blend, abs_source)
        level = os.path.splitext(rel_path)[0].replace("\\", "/").replace("/", "_")
        meta_deps_list.append(
            os.path.join(intermediate_root, level, "metadata.json").replace("\\", "/")
        )

    meta_deps = " ".join([escape_ninja(m) for m in meta_deps_list])

    # 1. Output blender extraction targets and map intermediate outputs
    for blend_path in blend_files:
        abs_blend = os.path.abspath(blend_path)
        abs_source = os.path.abspath(source_dir)
        rel_path = os.path.relpath(abs_blend, abs_source)
        level = os.path.splitext(rel_path)[0].replace("\\", "/").replace("/", "_")

        level_dir = os.path.join(intermediate_root, level).replace("\\", "/")
        meta_path = os.path.join(level_dir, "metadata.json").replace("\\", "/")

        # Direct Ninja dependency representing the Blender extraction rule
        ninja_content += f"\nbuild {escape_ninja(meta_path)}: blender_extract {escape_ninja(blend_path)} | {escaped_script}\n"

        if os.path.exists(meta_path):
            try:
                with open(meta_path, "r") as f:
                    manifest = json.load(f)
            except Exception as e:
                print(f"[Warning] Failed to parse {meta_path}: {e}")
                manifest = {}

            # Map individual Meshes
            for mesh in manifest.get("meshes", []):
                mesh_id = mesh.get("id")
                if not mesh_id:
                    continue

                bin_name = mesh.get("buffers", {}).get("bin_file")
                if not bin_name:
                    continue

                bin_file = os.path.join(level_dir, bin_name).replace("\\", "/")
                output_zmesh = f"build_assets/{level}/{mesh_id}.zmesh"
                virtual_path = f"{mesh_id}.zmesh"

                ninja_content += f"\nbuild {escape_ninja(output_zmesh)}: zmesh {escape_ninja(bin_file)} | {escaped_zcook}\n"
                ninja_content += f"  meta = {meta_path}\n"
                ninja_content += f"  id = {mesh_id}\n"
                compiled_targets.append(output_zmesh)
                manifest_entries.append(f"{virtual_path}={output_zmesh}")

            # Map Intermediate Textures
            tex_dir = os.path.join(level_dir, "textures")
            if os.path.exists(tex_dir):
                for tex in os.listdir(tex_dir):
                    in_path = os.path.join(tex_dir, tex).replace("\\", "/")
                    out_path = f"build_assets/{level}/lvl_{tex}.ztex"
                    virtual_path = f"textures/{tex}"

                    ninja_content += f"build {escape_ninja(out_path)}: ztex {escape_ninja(in_path)} | {escaped_zcook}\n"
                    compiled_targets.append(out_path)
                    manifest_entries.append(f"{virtual_path}={out_path}")

            # Emit Standard GLB Target
            output_glb = f"build_assets/debug_glb/{level}.glb"
            bin_dependencies = []
            for mesh in manifest.get("meshes", []):
                bin_name = mesh.get("buffers", {}).get("bin_file")
                if bin_name:
                    bin_dependencies.append(
                        os.path.join(level_dir, bin_name).replace("\\", "/")
                    )

            bin_dependencies = list(set(bin_dependencies))
            escaped_deps = " ".join([escape_ninja(d) for d in bin_dependencies])

            ninja_content += f"\nbuild {escape_ninja(output_glb)}: zglb {escape_ninja(meta_path)} | {escaped_deps} {escaped_zcook}\n"
            glb_targets.append(output_glb)

    # 2. Process Raw Loose Textures
    assets_root = os.path.join(source_dir, "resources", "assets")
    if os.path.exists(assets_root):
        for root, _, files in os.walk(assets_root):
            for file in files:
                if file.lower().endswith((".png", ".jpg", ".jpeg", ".tga")):
                    input_path = os.path.join(root, file).replace("\\", "/")
                    rel_path = os.path.relpath(input_path, assets_root).replace(
                        "\\", "/"
                    )
                    output_ztex = f"build_assets/raw/{rel_path}.ztex"

                    ninja_content += f"build {escape_ninja(output_ztex)}: ztex {escape_ninja(input_path)} | {escaped_zcook}\n"
                    compiled_targets.append(output_ztex)
                    manifest_entries.append(f"{rel_path}={output_ztex}")

    # 3. Write Manifest
    build_dir = os.path.dirname(output_file)
    manifest_dir = os.path.join(build_dir, "build_assets")
    os.makedirs(manifest_dir, exist_ok=True)
    manifest_target = os.path.join(manifest_dir, "manifest.txt").replace("\\", "/")

    with open(manifest_target, "w") as f:
        f.write("\n".join(manifest_entries))

    # 4. Final pack step: data/base.pak depends on the manifest, all compiled targets, and all metadata.json files
    escaped_targets = [escape_ninja(t) for t in compiled_targets]
    escaped_manifest = escape_ninja(manifest_target)
    escaped_meta_deps = [escape_ninja(m) for m in meta_deps_list]

    ninja_content += f"\nbuild data/base.pak: zpak {escaped_manifest} | {' '.join(escaped_targets)} {' '.join(escaped_meta_deps)}\n"

    # 5. Virtual targets
    escaped_glbs = [escape_ninja(g) for g in glb_targets]
    ninja_content += f"\nbuild debug_glbs: phony {' '.join(escaped_glbs)}\n"

    # 6. Self-Regeneration details
    escaped_configure = escape_ninja(
        os.path.join(source_dir, "configure_assets.py").replace("\\", "/")
    )
    escaped_output = escape_ninja(output_file)
    escaped_source = escape_ninja(source_dir)

    blend_deps = " ".join([escape_ninja(b) for b in blend_files])

    ninja_content += "\nrule regenerate_ninja\n"
    ninja_content += f"  command = python3 {escaped_configure} {escaped_output} {escaped_zcook} {escaped_source}\n"
    ninja_content += "  description = Regenerating assets.ninja\n"
    ninja_content += "  generator = 1\n"

    # Added both export_metadata.py and zcook to the self-regeneration dependencies
    ninja_content += f"\nbuild {escaped_output}: regenerate_ninja {escaped_configure} | {blend_deps} {meta_deps} {escaped_script} {escaped_zcook}\n"

    ninja_content += "\ndefault data/base.pak\n"

    with open(output_file, "w") as f:
        f.write(ninja_content)


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(
            "Usage: configure_assets.py <output_ninja_file> <zcook_executable> <source_dir>"
        )
        sys.exit(1)

    generate_ninja(sys.argv[1], sys.argv[2], sys.argv[3])
