#!/usr/bin/env python3
# configure_assets.py
import os
import sys
import json


def escape_ninja(path):
    # Ninja uses '$ ' to escape spaces in target and dependency paths
    return path.replace(" ", "$ ")


def generate_ninja(output_file, zcook_executable, source_dir):
    escaped_zcook = escape_ninja(zcook_executable)

    # Built-in Ninja variables ($in, $out) are auto-quoted by Ninja. DO NOT wrap in quotes.
    # Custom variables ($meta, $id) are NOT auto-quoted. DO wrap in quotes.
    ninja_content = f"""# Automatically generated by configure_assets.py
ninja_required_version = 1.3
builddir = build_assets

rule zmesh
  command = "{escaped_zcook}" mesh --meta "$meta" --id "$id" -i $in -o $out
  description = ZMESH $id

rule ztex
  command = "{escaped_zcook}" tex -i $in -o $out
  description = ZTEX $in

rule zglb
  command = "{escaped_zcook}" glb --meta $in -o $out
  description = ZGLB $in

rule zpak
  command = "{escaped_zcook}" pak -o $out -i $in
  description = ZPAK $out
  pool = console
"""

    compiled_targets = []
    glb_targets = []
    manifest_entries = []

    # 1. Process Intermediate Levels
    intermediate_root = os.path.join(source_dir, "resources", "intermediate")
    if os.path.exists(intermediate_root):
        for level in os.listdir(intermediate_root):
            level_dir = os.path.join(intermediate_root, level)
            if not os.path.isdir(level_dir):
                continue

            meta_path = os.path.join(level_dir, "metadata.json")
            if not os.path.exists(meta_path):
                continue

            with open(meta_path, "r") as f:
                manifest = json.load(f)

            # Map individual Meshes (namespaced by level folder name)
            for mesh in manifest.get("meshes", []):
                mesh_id = mesh.get("id")
                if not mesh_id:
                    continue

                bin_name = mesh.get("buffers", {}).get("bin_file")
                if not bin_name:
                    continue

                bin_file = os.path.join(level_dir, bin_name).replace("\\", "/")
                output_zmesh = f"build_assets/{level}/{mesh_id}.zmesh"
                virtual_path = f"{mesh_id}.zmesh"

                ninja_content += f"\nbuild {escape_ninja(output_zmesh)}: zmesh {escape_ninja(bin_file)}\n"
                ninja_content += f"  meta = {meta_path}\n"
                ninja_content += f"  id = {mesh_id}\n"
                compiled_targets.append(output_zmesh)
                manifest_entries.append(f"{virtual_path}={output_zmesh}")

            # Map Intermediate Textures (namespaced by level folder name)
            tex_dir = os.path.join(level_dir, "textures")
            if os.path.exists(tex_dir):
                for tex in os.listdir(tex_dir):
                    in_path = os.path.join(tex_dir, tex)
                    out_path = f"build_assets/{level}/lvl_{tex}.ztex"
                    virtual_path = f"textures/{tex}"

                    ninja_content += f"build {escape_ninja(out_path)}: ztex {escape_ninja(in_path)}\n"
                    compiled_targets.append(out_path)
                    manifest_entries.append(f"{virtual_path}={out_path}")

            # Emit Standard GLB Target for Debugging/External Viewers
            output_glb = f"build_assets/debug_glb/{level}.glb"
            bin_dependencies = []
            for mesh in manifest.get("meshes", []):
                bin_name = mesh.get("buffers", {}).get("bin_file")
                if bin_name:
                    bin_dependencies.append(
                        os.path.join(level_dir, bin_name).replace("\\", "/")
                    )

            bin_dependencies = list(set(bin_dependencies))
            escaped_deps = " ".join([escape_ninja(d) for d in bin_dependencies])

            ninja_content += f"\nbuild {escape_ninja(output_glb)}: zglb {escape_ninja(meta_path)} | {escaped_deps}\n"
            glb_targets.append(output_glb)

    # 2. Process Raw Loose Textures (Preserves relative directory paths to prevent collisions)
    assets_root = os.path.join(source_dir, "resources", "assets")
    if os.path.exists(assets_root):
        for root, _, files in os.walk(assets_root):
            for file in files:
                if file.lower().endswith((".png", ".jpg", ".jpeg", ".tga")):
                    input_path = os.path.join(root, file)
                    rel_path = os.path.relpath(input_path, assets_root).replace(
                        "\\", "/"
                    )
                    output_ztex = f"build_assets/raw/{rel_path}.ztex"

                    ninja_content += f"build {escape_ninja(output_ztex)}: ztex {escape_ninja(input_path)}\n"
                    compiled_targets.append(output_ztex)
                    manifest_entries.append(f"{rel_path}={output_ztex}")

    # 3. Write Manifest Directly from Python
    build_dir = os.path.dirname(output_file)
    manifest_dir = os.path.join(build_dir, "build_assets")
    os.makedirs(manifest_dir, exist_ok=True)
    manifest_target = os.path.join(manifest_dir, "manifest.txt").replace("\\", "/")

    with open(manifest_target, "w") as f:
        f.write("\n".join(manifest_entries))

    # 4. Final pack step: data/base.pak depends on the manifest and all compiled targets
    escaped_targets = [escape_ninja(t) for t in compiled_targets]
    escaped_manifest = escape_ninja(manifest_target)

    ninja_content += f"\nbuild data/base.pak: zpak {escaped_manifest} | {' '.join(escaped_targets)}\n"

    # 5. Add Virtual targets for clean organization
    escaped_glbs = [escape_ninja(g) for g in glb_targets]
    ninja_content += f"\nbuild debug_glbs: phony {' '.join(escaped_glbs)}\n"

    ninja_content += "\ndefault data/base.pak\n"

    with open(output_file, "w") as f:
        f.write(ninja_content)


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(
            "Usage: configure_assets.py <output_ninja_file> <zcook_executable> <source_dir>"
        )
        sys.exit(1)

    generate_ninja(sys.argv[1], sys.argv[2], sys.argv[3])
