// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

// File: tools/zshader/Emit.cpp
//
// The two files the tool writes, as text. The generated files are a contract --
// the engine compiles them, and the build only rewrites them when their content
// changes -- so the text that does not vary is written here the way the files
// read, and only what the catalog decides is formatted in. Nothing here reflects
// anything or parses an argument: it takes the model and returns the bytes.
//
// Four ways to add text, one per shape the emitter needs: Line for a formatted
// line, Verbatim for a line whose text is already final (the generated C++'s own
// punctuation, which std::format would read as replacement fields), Raw for a
// run of already-final text with the newlines written into it, and Blank for the
// empty lines that separate the generated blocks. None of them is called with a
// bare string meant to be formatted: a call with one argument is always text.

#include "ZShader.hpp"

#include <format>
#include <iterator>
#include <string>
#include <string_view>
#include <vector>

namespace ZHLN::ZShader {

namespace {

// The indent a binding list's entries sit at: the list is emitted inside a
// class body, four spaces past the line that opens it.
constexpr std::string_view kSlotIndent = "        ";

// One generated file, appended to a piece at a time. Everything the tool
// writes goes through here, so no call site has to remember where a line ends.
class Writer {
  public:
    explicit Writer(std::string& sink) noexcept: _out(sink) {
    }

    Writer(const Writer&)            = delete;
    Writer& operator=(const Writer&) = delete;

    // One line, formatted.
    template <typename... Args>
    void Line(std::format_string<Args...> fmt, Args&&... args) {
        Fragment(fmt, std::forward<Args>(args)...);
        Blank();
    }

    // A piece of a line: for the half a helper builds, like a binding list the
    // caller wraps in `using ... = ...;` on a line of its own.
    template <typename... Args>
    void Fragment(std::format_string<Args...> fmt, Args&&... args) {
        std::format_to(std::back_inserter(_out), fmt, std::forward<Args>(args)...);
    }

    // One line as it stands.
    void Verbatim(std::string_view text) {
        Raw(text);
        Blank();
    }

    // A run of text exactly as written, newlines and all.
    void Raw(std::string_view text) {
        _out.append(text);
    }

    // The empty line the generated files separate their blocks with.
    void Blank() {
        _out.push_back('\n');
    }

  private:
    std::string& _out;
};

// One module's binding list: the declarations the write side holds itself
// against, in the order the module declares them (set and binding ascending,
// which ReflectModule sorted). A module that declares none gets an empty list
// rather than a list with no entries.
auto BindingList(const std::vector<Descriptor>& descriptors, bool sampler, std::string_view indent) -> std::string {
    if (descriptors.empty()) {
        return "Vk::BindingList<>";
    }
    std::string text;
    Writer      out(text);
    out.Verbatim("Vk::BindingList<");
    for (size_t index = 0; index < descriptors.size(); ++index) {
        const Descriptor& descriptor = descriptors[index];
        const std::string entry      = sampler
                                           ? std::format("Vk::Declared::SamplerSlot<\"{}\", {}, {}>", descriptor.name, descriptor.set, descriptor.binding)
                                           : std::format("Vk::Declared::ResourceSlot<\"{}\", {}, {}, {}>", descriptor.name, descriptor.type, descriptor.set, descriptor.binding);
        out.Line("{}    {}{}", indent, entry, index + 1 == descriptors.size() ? "" : ",");
    }
    out.Fragment("{}>", indent);
    return text;
}

// One set's members: the modules whose bindings that descriptor block serves.
auto ModuleList(const std::vector<std::string>& types) -> std::string {
    std::string text;
    Writer      out(text);
    for (size_t index = 0; index < types.size(); ++index) {
        out.Fragment("{}{}", index == 0 ? "Modules::" : ", Modules::", types[index]);
    }
    return text;
}

// ShaderBindings.hpp up to the byte spans, which are one per input.
constexpr std::string_view kHeaderPreamble = R"ZHLN(// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

// File: <build>/generated_shaders/ShaderBindings.hpp
//
// GENERATED by tools/zshader from the cooked SPIR-V. Do not edit.
//
// One type per module: its entry point, its stage, the bindings it declares with
// their descriptor types and numbers, and the layout of its push-constant block.
// One `Vk::ShaderSet<...>` alias per pass, which is what a descriptor write names.
// No bytes: the modules themselves live in the generated ShaderBytecode.cpp, which
// is also where these lists are held against those bytes at compile time.

#pragma once

#include "Rendering.hpp" // the RHI implementation headers
#include "pipeline/ShaderProgram.hpp" // Vk::ShaderProgram, Vk::ShaderSet

#include <cstdint>
#include <span>
#include <string_view>

namespace ZHLN::ShaderLib {

/// One cooked module's bytes, defined in the generated ShaderBytecode.cpp --
/// the only translation unit in the project that #embeds them. Defined once,
/// so the image holds one copy of each module however many sites read it.
)ZHLN";

// ShaderBindings.hpp from the end of the byte spans to the first module type.
constexpr std::string_view kHeaderModulesOpen = R"ZHLN(
} // namespace ZHLN::ShaderLib

namespace ZHLN::Shaders {

/// The modules themselves. A set named after a pass (Lighting) is a different
/// declaration from the module it wraps, which is why the two live in separate
/// namespaces.
namespace Modules {
)ZHLN";

// The entry point and stage of one module: the two things a pipeline is built
// with, both read out of the module.
constexpr std::string_view kHeaderEntryPoint = R"ZHLN(
    /// The entry point the module declares, and the stage it was compiled
    /// for: what a pipeline is built with, read out of the module.
)ZHLN";

// Where the module lives, for a hot reload and for a reader that wants to
// compare the catalog against the file itself.
constexpr std::string_view kHeaderSource = R"ZHLN(
    /// The cooked module these declarations came from, for a hot reload and
    /// for a reader that wants to compare against the file itself.
)ZHLN";

// The push-constant block, when the module declares one.
constexpr std::string_view kHeaderPushOpen = R"ZHLN(
    /// The push-constant block the module declares: the size a push range
    /// needs and the members it is made of. The engine's own push struct is
    /// written by hand (it carries VkDeviceAddress and engine math types);
    /// this is what it can be held against.
)ZHLN";

// ShaderBindings.hpp from the end of the module types to the first set alias.
constexpr std::string_view kHeaderSetsOpen = R"ZHLN(
} // namespace Modules

/// One set per descriptor block: the modules whose bindings that block
/// serves. A write site names the set, and the set is what the compile-time
/// checks read.
)ZHLN";

// ShaderBindings.hpp's last line.
constexpr std::string_view kHeaderClose = R"ZHLN(
} // namespace ZHLN::Shaders
)ZHLN";

// ShaderBytecode.cpp up to the embedded modules.
constexpr std::string_view kSourcePreamble = R"ZHLN(// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

// File: <build>/generated_shaders/ShaderBytecode.cpp
//
// GENERATED by tools/zshader. Do not edit.
//
// The translation unit that #embeds every cooked module the catalog carries, and
// place where ShaderBindings.hpp is held against the modules it was generated
// from: every module's own bytes, walked here by SpirvBindings.hpp -- a reader
// that shares nothing with the SPIRV-Reflect the tool used -- must agree with
// the entry point, the stage and the binding lists the header states. A tool
// that reflected a module wrongly, and a header left stale by a rebuild, both
// fail to compile here instead of writing a descriptor nobody declared.

#include "ShaderBindings.hpp"

#include "pipeline/CatalogChecks.hpp" // ModuleMatchesBytes: the catalog held to the module's own bytes

#include <cstdint>
#include <span>

namespace {

)ZHLN";

// ShaderBytecode.cpp from the end of the embedded arrays to the span
// definitions they are read through.
constexpr std::string_view kSourceSpansOpen = R"ZHLN(} // namespace

namespace ZHLN::ShaderLib {

)ZHLN";

// ShaderBytecode.cpp from the end of the span definitions to the Bytes()
// definitions.
constexpr std::string_view kSourceBytesOpen = R"ZHLN(
} // namespace ZHLN::ShaderLib

namespace ZHLN::Shaders::Modules {

)ZHLN";

// ShaderBytecode.cpp from the end of the Bytes() definitions to the assertions
// that hold the catalog against the modules.
constexpr std::string_view kSourceChecksOpen = R"ZHLN(} // namespace ZHLN::Shaders::Modules

)ZHLN";

// The assertion's message: what a reader sees when the header and the module
// disagree, which is exactly the failure the two are here to catch.
constexpr std::string_view kSourceCheckMessage = R"ZHLN(    "ShaderBindings.hpp does not describe the module it was generated from (tools/zshader): regenerate, or fix the tool")ZHLN";

} // namespace

auto EmitHeader(const Options& options) -> std::string {
    std::string text;
    Writer      out(text);

    out.Raw(kHeaderPreamble);
    for (const BytesInput& input: BytesInputsOf(options)) {
        out.Line("extern const std::span<const uint8_t> {}; // {}", input.symbol, input.path);
    }
    out.Raw(kHeaderModulesOpen);

    for (const auto& [type, macro]: options.catalog) {
        const Module& module = ModuleFor(options, type, macro);

        out.Blank();
        out.Line("struct {} {{", type);
        out.Line("    using Resources = {};", BindingList(module.resources, false, kSlotIndent));
        out.Line("    using Samplers  = {};", BindingList(module.samplers, true, kSlotIndent));
        out.Raw(kHeaderEntryPoint);
        out.Line("    static constexpr const char*           EntryPoint = \"{}\";", module.entryPoint);
        out.Line("    static constexpr VkShaderStageFlagBits Stage      = {};", module.stage);
        out.Raw(kHeaderSource);
        out.Line("    static constexpr const char* Path     = \"{}\";", AsLiteral(module.path));
        out.Line("    static constexpr uint32_t    ByteSize = {};", module.byteSize);

        if (!module.pushes.empty()) {
            const PushBlock& push = module.pushes.front();
            out.Raw(kHeaderPushOpen);
            if (module.pushes.size() > 1) {
                out.Line("    /// (The module declares {} blocks; the first is", module.pushes.size());
                out.Verbatim("    /// what this build's pipelines take.)");
            }
            out.Line("    static constexpr uint32_t   PushSize = {};", push.paddedSize);
            out.Verbatim("    static constexpr Vk::PushMember Push[] = {");
            for (const PushMember& member: push.members) {
                out.Line("        {{\"{}\", {}, {}}},", member.name, member.offset, member.size);
            }
            out.Verbatim("    };");
        }

        out.Blank();
        out.Verbatim("    [[nodiscard]] static auto Bytes() -> std::span<const uint8_t>;");
        out.Verbatim("};");
    }

    out.Raw(kHeaderSetsOpen);
    for (const auto& [name, members]: options.sets) {
        out.Line("using {} = Vk::ShaderSet<{}>;", name, ModuleList(members));
    }
    out.Raw(kHeaderClose);
    return text;
}

auto EmitSource(const Options& options) -> std::string {
    std::string text;
    Writer      out(text);

    out.Raw(kSourcePreamble);
    for (const BytesInput& input: BytesInputsOf(options)) {
        out.Line("constexpr uint8_t {}_bytes[] = {{", input.symbol);
        out.Line("#embed \"{}\"", AsLiteral(input.path));
        out.Verbatim("};");
        out.Line("static_assert(sizeof({}_bytes) == {});", input.symbol, input.size);
        out.Blank();
    }

    out.Raw(kSourceSpansOpen);
    for (const BytesInput& input: BytesInputsOf(options)) {
        out.Line("const std::span<const uint8_t> {0} {{{0}_bytes}};", input.symbol);
    }

    out.Raw(kSourceBytesOpen);
    for (const auto& [type, macro]: options.catalog) {
        const Module& module = ModuleFor(options, type, macro);
        out.Line("auto {}::Bytes() -> std::span<const uint8_t> {{", type);
        out.Line("    return ZHLN::ShaderLib::{};", module.symbol);
        out.Verbatim("}");
        out.Blank();
    }

    out.Raw(kSourceChecksOpen);
    for (const auto& [type, macro]: options.catalog) {
        const Module& module = ModuleFor(options, type, macro);
        out.Line("// {} <- {}", type, module.path);
        out.Verbatim("static_assert(");
        out.Line("    ZHLN::Vk::ModuleMatchesBytes<ZHLN::Shaders::Modules::{0}>({1}_bytes),", type, module.symbol);
        out.Verbatim(kSourceCheckMessage);
        out.Verbatim(");");
        out.Blank();
    }
    return text;
}

} // namespace ZHLN::ZShader
