// Copyright (C) 2026 Evilpasture | evilpasture+github@proton.me
// SPDX-License-Identifier: GPL-3.0-or-later

// File: tools/zshader/ZShader.hpp
//
// The catalog zshader builds, as data: what one module declares, and what
// the build asked the tool for. Slang compiles it (SlangReflect.cpp),
// reflection names it (Reflect.cpp), the emitters read it (Emit.cpp) and the
// command line owns it (main.cpp) -- so the model is what the four parts of
// the tool have in common instead of a shape each of them spells out again.
//
// The tool runs before the engine is built, so it cannot link the engine even
// though it is allowed to use it: the engine links zahlen_render, which compiles
// the catalog this tool writes, and a link edge back would be a cycle. What is
// used from the engine is header-only -- the reflection helpers behind
// Reflect::EnumToString (Reflect.cpp) and ZHLN::Ranges (main.cpp) -- and the
// tool's own diagnostics are one-line prints, which is the same choice zcook
// makes for its half of the build.

#pragma once

#include <cstdint>
#include <cstdlib>
#include <format>
#include <map>
#include <print>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace ZHLN::ZShader {

// One member of a module's push-constant block: where it sits, how big it is,
// and the name the shader knows it by.
struct PushMember {
    std::string name;
    uint32_t    offset = 0;
    uint32_t    size   = 0;
};

// One descriptor a module declares: the name the shader knows it by, the
// descriptor type as the engine spells it, and where the module put it.
//
// The type is a view because it is the enumerator's own name: reflection
// returns a string that outlives the model, and the generated header wants the
// spelling the engine's headers use, not a copy of it.
struct Descriptor {
    std::string      name;
    std::string_view type; // "VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE", the enumerator's own name
    uint32_t         set     = 0;
    uint32_t         binding = 0;
};

// One push-constant block a module DECLARES (which is not the same as one the
// emitted module carries: the usage table stops before the push category, so
// the catalog keeps every declaration). The block's padded extent and its
// members reach the generated header -- member offsets are block-relative,
// exactly as the cooked bytes carry them; the block's own name and unpadded
// size are SPIR-V's business, not the catalog's.
struct PushBlock {
    uint32_t                paddedSize = 0;
    std::vector<PushMember> members;
};

// One cooked module, as the generated files see it: the symbol it is embedded
// under, the file it came from, and -- once reflected -- everything the header
// declares about it. A module the catalog does not carry (`--bytes` without a
// `--module`) is only the first four fields.
struct Module {
    std::string      macro;  // SHADER_LIGHTING_SLANG_PS_PATH
    std::string      symbol; // shader_lighting_slang_ps_path
    std::string      path;   // the cooked .spv, as the build named it
    uint32_t         byteSize = 0;
    std::string      entryPoint;
    std::string_view stage; // "VK_SHADER_STAGE_FRAGMENT_BIT", the enumerator's own name
    bool             reflected = false;
    std::vector<Descriptor> resources;
    std::vector<Descriptor> samplers;
    std::vector<PushBlock>  pushes;
};

// How to compile the module a macro names: the Slang source, the entry point
// and stage the cook selected, and the -D flags it passed (name, value). A
// bare -DNAME arrives with value "1": defined()-ness is all any shader asks,
// and Slang wants a value for every macro it is given.
struct SlangSource {
    std::string path;
    std::string entry;
    std::string stage; // vertex, fragment, compute, amplification, mesh
    std::vector<std::pair<std::string, std::string>> defines;
};

// One cooked module, or one data blob, as the generated byte file sees it: a
// symbol to name it by, the file the bytes come from, and its size.
struct BytesInput {
    std::string symbol;
    std::string path;
    uint32_t    size = 0;
};

// What the command line asked for: the files to write, the modules to embed,
// how each of them compiles (macro -> source, kept sorted so a failure names
// the same macro on every run), the data blobs next to them, the catalog's
// types (type name -> macro, kept sorted so the header is stable across
// runs), and one alias per descriptor block.
struct Options {
    std::string                        outHeader;
    std::string                        outSource;
    std::vector<Module>                modules; // one per --bytes, in the order given
    std::map<std::string, SlangSource> slangSources; // one per --slang-source, sorted by macro
    std::vector<BytesInput>            blobs;   // one per --blob, in the order given
    std::map<std::string, std::string> catalog; // one per --module, sorted by type name
    std::vector<std::pair<std::string, std::vector<std::string>>> sets; // one per --set, in the order given
};

// Reports a build configuration the tool cannot carry on from: one line on
// stderr, prefixed with the tool's name, and a non-zero exit.
//
// Not an exception: the tool is built with -fno-exceptions like the engine.
// Not ZHLN::Log either -- the engine's log is not header-only and cannot be
// linked here (see the file comment), and its [file:line] [Fiber:...] context
// belongs in the engine's log, not in a build step's diagnostics.
template <typename... Args>
[[noreturn]] void Fail(std::format_string<Args...> fmt, Args&&... args) {
    std::println(stderr, "zshader: {}", std::format(fmt, std::forward<Args>(args)...));
    std::exit(1);
}

// Compiles one module in place from its Slang source and reflects it: entry
// point, stage, descriptors, push blocks. Refuses anything the engine's model
// cannot carry -- a module is one entry point, and every descriptor must have
// a name a write can be held against.
void ReflectModule(Module& module, const SlangSource& source, const std::vector<std::string>& searchPaths);

// True when this translation unit can name enumerators at all: a compiler with
// reflection, or a copy of this file that went through the AST transpiler. The
// stubs name every value the same thing, so a value that certainly has a name
// is what tells the two apart -- see Reflect.cpp.
auto NamesEnumerators() -> bool;

// The generated header: one type per module, one `Vk::ShaderSet<...>` alias per
// descriptor block, no bytes.
auto EmitHeader(const Options& options) -> std::string;

// The generated byte file: `#embed` per input, the spans the engine reads them
// through, and the static_asserts that hold the header against the modules.
auto EmitSource(const Options& options) -> std::string;

// The whole command line: parses the arguments, reflects every `--bytes` module
// and writes the two files. Returns the process exit code.
auto RunCommandLine(int argc, char** argv) -> int;

// The gpu-types mode: compiles the gpu_abi module in-process and walks its
// reflected layout into the generated host structs (GeneratedGpuTypes.hpp),
// the single source of truth <Zahlen/Render/GpuLayout.hpp> re-exports -- plus the
// module's own SPIR-V, the gpu-abi check's input. See GpuTypes.cpp, which is
// the mode's only translation unit.
struct GpuTypesOptions {
    std::string              module;      // gpu_abi: the module to compile
    std::vector<std::string> searchPaths; // one per --slang-search, in the order given
    std::string              outStructs;
    std::string              outSpv;
};

void RunGpuTypesMode(const GpuTypesOptions& options);

// Writes `content` to `path`, unless the file already says exactly that: the
// generated files are inputs to the build, so rewriting an identical one
// would recompile every translation unit that includes it. True when the
// file was written.
auto WriteFileIfChanged(const std::string& path, const std::string& content) -> bool;

// `SHADER_FOO_BAR_PATH` -> `shader_foo_bar_path`, the name the byte span is
// defined under.
auto ToSymbol(std::string_view macro) -> std::string;

// True for a name a C++ declaration can carry.
auto IsIdentifier(std::string_view name) -> bool;

// A path as the body of a C++ string literal: escaped backslashes and quotes,
// so a Windows-style path survives the round trip.
auto AsLiteral(std::string_view text) -> std::string;

// One file, verbatim. Fails the build when it cannot be read, because a tool
// that skips a file it was told to read produces a catalog that silently lacks
// it.
auto ReadFile(const std::string& path) -> std::vector<uint8_t>;

// `Name=rest` split at the first separator, both halves empty when there is
// none: the shape every `--flag Name=Value` argument has.
auto SplitOnce(std::string_view text, char separator) -> std::pair<std::string_view, std::string_view>;

// The comma-separated half of a `--set` argument, empty entries dropped.
auto SplitList(std::string_view text, char separator) -> std::vector<std::string>;

// Every byte input, modules first: the order the generated file embeds them in.
auto BytesInputsOf(const Options& options) -> std::vector<BytesInput>;

// The reflected module a catalog type names. A type whose macro no `--bytes`
// input carries is a build configuration mistake, not a tool bug: the build
// names both sides, so the message says which pair disagreed.
auto ModuleFor(const Options& options, std::string_view type, std::string_view macro) -> const Module&;

} // namespace ZHLN::ZShader
