// tools/ecsc/src/codegen.rs
// Copyright (C) 2026 Evilpasture | SPDX-License-Identifier: GPL-3.0-or-later

use crate::ast::*;
use regex::Regex;
use std::collections::HashSet;

pub struct CXXModuleGenerator<'a> {
    ast: &'a AST,
    module_name: String,
}

impl<'a> CXXModuleGenerator<'a> {
    pub fn new(ast: &'a AST, module_name: &str) -> Self {
        Self {
            ast,
            module_name: module_name.to_string(),
        }
    }

    pub fn generate_cppm(&self) -> String {
        let mut code = String::new();
        code.push_str("// Automatically generated by ecsc (Rust). DO NOT EDIT.\nmodule;\n\n");
        code.push_str("#include <Zahlen/Engine.hpp>\n");
        code.push_str("#include <Zahlen/Components.hpp>\n");
        code.push_str("#include <Zahlen/ecs/ECS.hpp>\n");
        code.push_str("#include <Zahlen/Core/Reflection.hpp>\n\n");
        code.push_str(&format!("export module {};\n\n", self.module_name));
        code.push_str(&format!("export namespace {} {{\n\n", self.module_name));

        code.push_str(
            "// ============================================================================\n",
        );
        code.push_str("// EXPORTED COMPONENTS\n");
        code.push_str(
            "// ============================================================================\n",
        );
        for comp in &self.ast.components {
            code.push_str(&format!("struct {} {{\n", comp.name));
            for f in &comp.fields {
                let default_str = f
                    .default_value
                    .as_ref()
                    .map_or("".to_string(), |v| format!(" = {}", v));
                code.push_str(&format!("    {} {}{};\n", f.type_name, f.name, default_str));
            }
            code.push_str("};\n\n");
        }

        code.push_str(
            "// ============================================================================\n",
        );
        code.push_str("// EXPORTED BLUEPRINTS & BEHAVIORS\n");
        code.push_str(
            "// ============================================================================\n",
        );
        for ent in &self.ast.entities {
            code.push_str(&format!("namespace {} {{\n", ent.name));
            let mut all_comps: Vec<String> =
                ent.components.iter().map(|c| c.name.clone()).collect();
            all_comps.extend(ent.uses.clone());

            let params_str = all_comps
                .iter()
                .map(|c| format!("const {}& _{} = {{}}", c, c.to_lowercase()))
                .collect::<Vec<_>>()
                .join(", ");

            code.push_str(&format!(
                "    inline ZHLN::Entity Spawn(ZHLN::ECS::Registry& reg, {}) {{\n",
                params_str
            ));
            code.push_str("        ZHLN::Entity e = reg.Create();\n");
            for c in &all_comps {
                code.push_str(&format!("        reg.Add(e, _{});\n", c.to_lowercase()));
            }
            code.push_str("        return e;\n    }\n\n");

            for beh in &ent.behaviors {
                let mut param_list = vec![
                    "ZHLN::ECS::Registry& reg".to_string(),
                    "ZHLN::Entity entity".to_string(),
                ];
                for p in &beh.params {
                    param_list.push(format!("{} {}", p.type_name, p.name));
                }
                let params_decl = param_list.join(", ");

                code.push_str(&format!(
                    "    inline void {}({}) {{\n",
                    beh.name, params_decl
                ));

                let mut body_transformed = beh.body.clone();
                for comp in &self.ast.components {
                    let pattern = format!(r"\b{}\b", comp.name);
                    let re = Regex::new(&pattern).unwrap();
                    if re.is_match(&body_transformed) {
                        let comp_var = format!("_{}", comp.name.to_lowercase());
                        code.push_str(&format!(
                            "        auto* {} = reg.Get<{}>(entity);\n",
                            comp_var, comp.name
                        ));
                        code.push_str(&format!("        if (!{}) return;\n", comp_var));
                        body_transformed = re
                            .replace_all(&body_transformed, comp_var.as_str())
                            .to_string();
                    }
                }
                code.push_str(&format!("        {};\n    }}\n", body_transformed));
            }

            code.push_str(&format!("}} // namespace {}\n\n", ent.name));
        }

        code.push_str("void RegisterAll(ZHLN::Engine& engine);\n\n");
        code.push_str(&format!("}} // export namespace {}\n", self.module_name));
        code
    }

    pub fn generate_cpp(&self) -> String {
        let mut code = String::new();
        code.push_str("// Automatically generated by ecsc (Rust). DO NOT EDIT.\nmodule;\n\n");
        code.push_str("#include <Zahlen/Engine.hpp>\n");
        code.push_str("#include <Zahlen/ecs/ECS.hpp>\n");
        code.push_str("#include <Zahlen/ScriptBinder.hpp>\n\n");
        code.push_str(&format!("module {};\n\n", self.module_name));
        code.push_str(&format!("namespace {} {{\n\n", self.module_name));

        for sys_def in &self.ast.systems {
            code.push_str(&format!(
                "static void Exec_{}(ZHLN::Engine& engine, float {}) {{\n",
                sys_def.name, sys_def.execute_param
            ));
            code.push_str("    auto& reg = engine.GetRegistry();\n");

            let query_comp = if !sys_def.writes.is_empty() {
                &sys_def.writes[0]
            } else {
                &sys_def.reads[0]
            };
            code.push_str(&format!(
                "    auto entities = reg.GetEntitiesWith<{}>();\n",
                query_comp
            ));
            code.push_str(&format!(
                "    auto primaryArray = reg.GetRawArray<{}>();\n\n",
                query_comp
            ));

            code.push_str("    for (size_t i = 0; i < entities.size(); ++i) {\n");
            code.push_str("        ZHLN::Entity e = entities[i];\n");

            let mut all_sys_comps: HashSet<&String> = sys_def.reads.iter().collect();
            all_sys_comps.extend(sys_def.writes.iter());

            for comp in all_sys_comps {
                if comp == query_comp {
                    code.push_str(&format!("        auto& {} = primaryArray[i];\n", comp));
                } else {
                    let comp_var = format!("_{}", comp.to_lowercase());
                    code.push_str(&format!(
                        "        auto* {} = reg.Get<{}>(e);\n",
                        comp_var, comp
                    ));
                    code.push_str(&format!("        if (!{}) continue;\n", comp_var));
                    code.push_str(&format!("        auto& {} = *{};\n", comp, comp_var));
                }
            }

            code.push_str(&format!("        {};\n", sys_def.execute_body));
            code.push_str("    }\n}\n\n");
        }

        code.push_str("void RegisterAll(ZHLN::Engine& engine) {\n");
        code.push_str("    auto& reg = engine.GetRegistry();\n");
        for comp in &self.ast.components {
            code.push_str(&format!(
                "    reg.RegisterComponent<{}>(\"{}\");\n",
                comp.name, comp.name
            ));
        }

        code.push_str("\n    // Register components with ScriptBinder for Fennel / Lua\n");
        for comp in &self.ast.components {
            code.push_str(&format!(
                "    ZHLN::ScriptBinder::Get().Register<{}>();\n",
                comp.name
            ));
        }

        code.push_str("\n    auto& graph = engine.GetUpdateGraph();\n");
        for sys_def in &self.ast.systems {
            let mut accesses = Vec::new();
            for r in &sys_def.reads {
                accesses.push(format!("ZHLN::ECS::Read<{}>()", r));
            }
            for w in &sys_def.writes {
                accesses.push(format!("ZHLN::ECS::Write<{}>()", w));
            }

            code.push_str("    graph.AddSystem({\n");
            code.push_str(&format!(
                "        .update_func = [](ZHLN::Engine& eng, float dt) {{ Exec_{}(eng, dt); }},\n",
                sys_def.name
            ));
            code.push_str(&format!("        .name = \"{}\",\n", sys_def.name));
            code.push_str(&format!(
                "        .access_pattern = {{ {} }},\n",
                accesses.join(", ")
            ));
            code.push_str("        .enabled = true\n    });\n");
        }

        code.push_str("}\n\n");
        code.push_str(&format!("}} // namespace {}\n", self.module_name));
        code
    }
}
